# Generated by Django 5.2.8 on 2025-11-28 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('wb_link', models.URLField(verbose_name='Ссылка на WB')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена выкупа')),
                ('cashback', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма кэшбэка')),
                ('total_slots', models.IntegerField(verbose_name='Всего мест')),
                ('active', models.BooleanField(default=True, verbose_name='Активен (в каталоге)')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Каталог товаров',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает скрина'), ('review', 'На проверке'), ('approved', 'Оплачено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='proofs/', verbose_name='Скриншот выкупа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.telegramuser')),
            ],
            options={
                'verbose_name': 'Выкуп',
                'verbose_name_plural': 'Заказы/Выкупы',
            },
        ),
    ]
