# Generated by Django 5.2.8 on 2025-11-29 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Выкуп', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Реквизиты (Тел/Карта)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает выплаты'), ('paid', 'Выплачено'), ('rejected', 'Отклонено (возврат)')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на вывод',
                'verbose_name_plural': 'Заявки на вывод',
            },
        ),
    ]
