# Generated by Django 5.2.8 on 2025-12-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', '📦 Заказан (на проверке)'), ('received', '✅ Получен'), ('reviewed', '⭐ Отзыв написан'), ('approved', '💰 Выплачено (Архив)'), ('rejected', '❌ Отклонено')], default='ordered', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (инструкция)'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Реквизиты'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает выплаты'), ('paid', 'Выплачено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'product')},
        ),
    ]
