# Generated by Django 5.2.8 on 2025-12-09 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_status_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_slots',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wb_link',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='created_at',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='payment_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сохраненные реквизиты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/', verbose_name='Скриншот'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Заказан (на проверке)'), ('received', 'Получен'), ('approved', 'Выплачено (Архив)'), ('rejected', 'Отклонено')], default='ordered', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cashback',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кэшбэк'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Выплачено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.telegramuser')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Корзины пользователей',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
