# Generated by Django 5.2.8 on 2025-12-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='checks/', verbose_name='Скрин Чека'),
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Артикул WB'),
        ),
        migrations.AddField(
            model_name='product',
            name='cashback_percent',
            field=models.IntegerField(default=100, verbose_name='% Кэшбэка'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='product',
            name='wb_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена на WB'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/', verbose_name='Скрин ЛК'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Заказан (Ждет фото)'), ('check_wait', 'Ждет чек'), ('received', 'Получен (На проверке)'), ('approved', 'Выплачено (Архив)'), ('rejected', 'Отклонено')], default='ordered', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Кэшбэк (фиксир.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (в боте)'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='payment_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Реквизиты'),
        ),
    ]
