# Generated by Django 5.2.8 on 2025-12-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер с чека'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Заказан (Ждет фото)'), ('check_wait', 'Ждет чек'), ('number_wait', 'Ждет номер чека'), ('received', 'Получен (На проверке)'), ('approved', 'Выплачено (Архив)'), ('rejected', 'Отклонено')], default='ordered', max_length=20, verbose_name='Статус'),
        ),
    ]
